[package]
name = "escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
test-sbf = []

[dependencies]
solana-program = "2.1"
spl-token = { version = "7.0.0", features = ["no-entrypoint"] }
wasm-bindgen = "0.2.100"

[dev-dependencies]
mollusk-svm = "0.0.15"
mollusk-svm-programs-token = "0.0.15"
solana-sdk = "2.1"
